'use strict';

module.exports = {
	'SET_LECTURES': 'SET_LECTURES',
  'SET_QUESTIONS': 'SET_QUESTIONS',
  'SET_COURSES': 'SET_COURSES',
  'SET_PLAYLIST': 'SET_PLAYLIST',
  'SET_LECTURE_INFO': 'SET_LECTURE_INFO'
};
