'use strict';

module.exports = {
	'SET_LECTURES': 'SET_LECTURES',
  'SET_COURSES': 'SET_COURSES',
  'SET_PLAYLIST': 'SET_PLAYLIST',
  'SET_LECTURE_INFO': 'SET_LECTURE_INFO',
  'SET_QUESTIONS': 'SET_QUESTIONS'
};
